### ISSUE TITLE
ModForgery Cleanup

### ISSUE THREAD

**Issue by xbony2** [RollercoasterTeam/Rollercoaster#10]
ModForgery is kind of deadish... however, it bothers me that the repos ElectroSuits and ForgeryLauncher are empty and taking up space; they should probably be deleted or moved. Anyone for/against?

**Comment by tattyseal** [comment]
Move the repositories to your own accounts. Its been 6 months.

**Comment by modmuss50** [comment]
@klmDF14J make a rollercoster team then move it to there? We can keep all the commits. yes or no?

**Comment by modmuss50** [comment]
And if a repo is empty contact the creator and ask them if they want to to be deleted

**Comment by klmDF14J** [comment]
Yes go ahead

**Comment by klmDF14J** [comment]
And make that rollercoaster team
